### ISSUE TITLE
[Bug]: COG overviews dominated by NaNs

### ISSUE THREAD

**Issue by scottyhq** [opera-adt/RTC#79]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

First, thank you for such a great product and keeping the development on GitHub! In my first attempt to work with the RTC Files from ASF DAAC I noticed the COG overviews are dominated by NaNs and very small size. 

<img width="893" alt="image" src="https://github.com/opera-adt/RTC/assets/3924836/fcb0bbed-025d-47cd-a5ec-60b0414b2e35">

This bug affects the quality of displaying web map tiles directly from the COGs and also it's a common analysis workflow to start with overviews for fast prototyping before going to full resolution.

### What did you expect?

I expect overview resampling to take into account NaN values such that they are averaged out at lower resolution levels. Also factor-of-2 zoom levels could be more useful given the starting resolution as the smaller zoom pyramids are extremely tiny.

Seems this could be the place for such changes? https://github.com/opera-adt/RTC/blob/70d42164a5ebff07165f551c619b3e3da2a5e51d/src/rtc/core.py#L59

### Reproducible steps

```python
import xarray as xr #2023.2.0
import matplotlib.pyplot as plt
import os 

# Uses ~/.netrc with nasa credentials
os.environ['GDAL_DISABLE_READDIR_ON_OPEN']='EMPTY_DIR'
os.environ['GDAL_HTTP_COOKIEJAR']='/tmp/cookies.txt'
os.environ['GDAL_HTTP_COOKIEFILE']='/tmp/cookies.txt'

rtcFile = 'OPERA_L2_RTC-S1_T013-026571-IW1_20231112T142222Z_20231113T010035Z_S1A_30_v1.0_VH.tif'
url = f'https://datapool.asf.alaska.edu/RTC/OPERA-S1/{rtcFile}'


fig,axes = plt.subplots(1,5,
                        figsize=(16,6), 
                        sharex=True, sharey=True, 
                       )

for i in range(-1,4):
    ax=axes[i+1]
    da = xr.open_dataarray(url, engine='rasterio',
                           open_kwargs={"overview_level": i}
                          ).squeeze()
    
    da.isnull().plot.imshow(ax=ax, add_colorbar=False)
    ax.set_title(f'overview_level={i}\n{da.shape}')
    ax.set_aspect(1)
```

### Environment

```bash
https://opensciencelab.asf.alaska.edu
```

**Comment by gshiroma** [comment]
Hi @scottyhq , thank you for reporting this issue! You are right, the OPERA RTC-S1 products produced as of today do present this problem. We were able to track this issue down, and we found out the problem is in the re-generation of overviews after this RTC-S1 software (Science Application Software) is executed. 

I was informed me that this needs to be done because the RTC-S1 products metadata needs to be updated later in the process and that invalidates the COG format. The problem is that this second processing is not using the overview sampling algorithm set to "AVERAGE", as we have [here](https://github.com/opera-adt/RTC/blob/70d42164a5ebff07165f551c619b3e3da2a5e51d/src/rtc/rtc_s1.py#L1075).

So, the issue is not really in this RTC-S1 software. But I'll keep this issue open until the OPERA Science Data System fix it on their side. Thank again!

**Comment by hjkristenson** [comment]
It looks like this issue has been addressed on the SDS side. There are OPERA RTC products with good overviews starting April 1, 2024. There are duplicate products in the archive, however, so users have to take care to use products that were processed April 18 or later. Are there any details available about the implementation of this change? It looks like there was no change in the PGE version in the metadata for the new products.

**Comment by gshiroma** [comment]
Thank you for the feedback @hjkristenson ! The software version (`SOFTWARE_VERSION` for GeoTIFF files or `/metadata/sourceData/softwareVersion` for the HDF5 file) has been updated from `1.0.1` to `1.0.2`. It looks like the SDS team kept the same product version as `1.0`. Does this answer your question?
